// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RetrieveDetails(arg1) {
  return window['go']['main']['App']['RetrieveDetails'](arg1);
}

export function RetrievePokemons() {
  return window['go']['main']['App']['RetrievePokemons']();
}

export function SendRequest(arg1, arg2) {
  return window['go']['main']['App']['SendRequest'](arg1, arg2);
}
