// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Greet(arg1:string):Promise<string>;

export function RetrieveDetails(arg1:string):Promise<models.PokemonDetail>;

export function RetrievePokemons():Promise<models.PokemonResponse>;

export function SendRequest(arg1:string,arg2:string):Promise<string>;
